version: '3.3'
services:
    postgress:
        #puede ser cuallquier nomnbre
        image: postgres:13
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=prueba_postgress
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=root@admin.com
            - PGADMIN_DEFAULT_PASSWORD=prueba_pgadmin
        ports:
            - 5050:80
        depends_on:
            - postgress
    mysql:
        #puede ser cuallquier nomnbre
        image: mysql:5
        environment:
            - MYSQL_DATABASE=mydb
            - MYSQL_ROOT_PASSWORD=prueba_mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=prueba_mysql
            - PMA_HOST=mysql
        ports:
            - 8080:80
        depends_on:
            - mysql
